---
# tasks file for apache-server
- name: install yum latest packages
  yum: 
   name: "*"
   state: present 
   
- name: Install Apache.
  yum:
    name:
      - httpd
      - httpd-devel
    state: present

- name: Ensure Apache started
  service:
    name: httpd
    state: started
    enabled: true
 
