---
# tasks file for apache-server

- name: upgrade all packages
  yum: name=* state=latest
   
- name: Install Apache.
  yum:
    name:
      - httpd
      - httpd-devel
    state: present

- name: Ensure Apache started
  service:
    name: httpd
    state: started
    enabled: true
 
